In [5]:
import pandas as pd

print(pd.__version__)

3.0.0

In [6]:
df = pd.read_csv("gsearch_jobs.csv")
df.head()

,Unnamed: 0,index,title,company_name,location,via,description,extensions,job_id,thumbnail,...,commute_time,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens
0,0,0,Data Analyst,Meta,Anywhere,via LinkedIn,In the intersection of compliance and analytic...,"['15 hours ago', '101K–143K a year', 'Work fro...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,101K–143K,a year,122000.0,101000.0,143000.0,NaN,122000.0,122000.0,"['tableau', 'r', 'python', 'sql']"
1,1,1,Data Analyst,ATC,United States,via LinkedIn,Job Title: Entry Level Business Analyst / Prod...,"['12 hours ago', 'Full-time', 'Health insurance']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
2,2,2,Aeronautical Data Analyst,"Garmin International, Inc.","Olathe, KS",via Indeed,Overview:\n\nWe are seeking a full-time...\nAe...,"['18 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJBZXJvbmF1dGljYWwgRGF0YSBBbm...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['sql']
3,3,3,Data Analyst - Consumer Goods - Contract to Hire,Upwork,Anywhere,via Upwork,Enthusiastic Data Analyst for processing sales...,"['12 hours ago', '15–25 an hour', 'Work from h...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgLSBDb25zdW...,NaN,...,NaN,15–25,an hour,20.0,15.0,25.0,20.0,NaN,41600.0,"['powerpoint', 'excel', 'power_bi']"
4,4,4,Data Analyst | Workforce Management,Krispy Kreme,United States,via LinkedIn,Overview of Position\n\nThis position will be ...,"['7 hours ago', '90K–110K a year', 'Contractor']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgfCBXb3JrZm...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,90K–110K,a year,100000.0,90000.0,110000.0,NaN,100000.0,100000.0,"['powerpoint', 'excel', 'outlook', 'word']"

In [7]:
df.shape

(61953, 27)

In [8]:
df.columns

Index(['Unnamed: 0', 'index', 'title', 'company_name', 'location', 'via',
       'description', 'extensions', 'job_id', 'thumbnail', 'posted_at',
       'schedule_type', 'work_from_home', 'salary', 'search_term', 'date_time',
       'search_location', 'commute_time', 'salary_pay', 'salary_rate',
       'salary_avg', 'salary_min', 'salary_max', 'salary_hourly',
       'salary_yearly', 'salary_standardized', 'description_tokens'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 61953 entries, 0 to 61952
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           61953 non-null  int64
 1   index                61953 non-null  int64
 2   title                61953 non-null  str
 3   company_name         61953 non-null  str
 4   location             61916 non-null  str
 5   via                  61944 non-null  str
 6   description          61953 non-null  str
 7   extensions           61953 non-null  str
 8   job_id               61953 non-null  str
 9   thumbnail            38194 non-null  str
 10  posted_at            61763 non-null  str
 11  schedule_type        61707 non-null  str
 12  work_from_home       27980 non-null  object
 13  salary               10088 non-null  str
 14  search_term          61953 non-null  str
 15  date_time            61953 non-null  str
 16  search_location      61953 non-null  str
 17  commute_time         0 non-null      float64
 18  salary_pay           10088 non-null  str
 19  salary_rate          10088 non-null  str
 20  salary_avg           10088 non-null  float64
 21  salary_min           9512 non-null   float64
 22  salary_max           9512 non-null   float64
 23  salary_hourly        5900 non-null   float64
 24  salary_yearly        4069 non-null   float64
 25  salary_standardized  10088 non-null  float64
 26  description_tokens   61953 non-null  str
dtypes: float64(7), int64(2), object(1), str(17)
memory usage: 12.8+ MB

In [10]:

df.isnull().sum()

Unnamed: 0                 0
index                      0
title                      0
company_name               0
location                  37
via                        9
description                0
extensions                 0
job_id                     0
thumbnail              23759
posted_at                190
schedule_type            246
work_from_home         33973
salary                 51865
search_term                0
date_time                  0
search_location            0
commute_time           61953
salary_pay             51865
salary_rate            51865
salary_avg             51865
salary_min             52441
salary_max             52441
salary_hourly          56053
salary_yearly          57884
salary_standardized    51865
description_tokens         0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['title'].value_counts().head(20)

title
Data Analyst                              6444
Senior Data Analyst                       1748
Data Scientist                             931
Data Analyst II                            644
Business Data Analyst                      495
Lead Data Analyst                          428
Survey Data Analyst                        422
Data Engineer                              375
Business Intelligence Analyst              343
Data Analyst III                           284
Sr. Data Analyst, Marketing Operations     271
Sr. Data Analyst                           240
Financial Data Analyst                     227
Marketing Data Analyst                     223
Junior Data Analyst                        213
Business Analyst                           212
Data analyst                               163
Healthcare Data Analyst                    162
Data Analyst I                             159
Sr Data Analyst                            155
Name: count, dtype: int64

In [14]:
# 1. Most common job titles
print("TOP JOB TITLES")
print(df['title'].value_counts().head(20))

# 2. Employment / schedule types
print("\nSCHEDULE TYPES")
print(df['schedule_type'].value_counts().head(15))

# 3. Remote work
print("\nWORK FROM HOME")
print(df['work_from_home'].value_counts(dropna=False))

# 4. Search locations
print("\nSEARCH LOCATIONS")
print(df['search_location'].value_counts().head(15))

# 5. Salary availability
print("\nSALARY DATA")
print(df['salary'].notna().value_counts())

# 6. Salary rate
print("\nSALARY RATE")
print(df['salary_rate'].value_counts(dropna=False).head(10))

TOP JOB TITLES
title
Data Analyst                              6444
Senior Data Analyst                       1748
Data Scientist                             931
Data Analyst II                            644
Business Data Analyst                      495
Lead Data Analyst                          428
Survey Data Analyst                        422
Data Engineer                              375
Business Intelligence Analyst              343
Data Analyst III                           284
Sr. Data Analyst, Marketing Operations     271
Sr. Data Analyst                           240
Financial Data Analyst                     227
Marketing Data Analyst                     223
Junior Data Analyst                        213
Business Analyst                           212
Data analyst                               163
Healthcare Data Analyst                    162
Data Analyst I                             159
Sr Data Analyst                            155
Name: count, dtype: int64

SCHEDULE TYPES
schedule_type
Full-time                               45082
Contractor                               9284
Contractor and Temp work                 3130
Full-time and Part-time                  1187
Part-time                                1144
Internship                                516
Full-time and Contractor                  349
Full-time and Temp work                   283
Full-time and Internship                  192
Temp work                                 169
Full-time, Part-time, and Internship       92
Full-time, Contractor, and Temp work       85
Part-time, Contractor, and Temp work       47
Part-time and Contractor                   30
Volunteer                                  27
Name: count, dtype: int64

WORK FROM HOME
work_from_home
NaN     33973
True    27980
Name: count, dtype: int64

SEARCH LOCATIONS
search_location
United States    61953
Name: count, dtype: int64

SALARY DATA
salary
False    51865
True     10088
Name: count, dtype: int64

SALARY RATE
salary_rate
NaN        51865
an hour     5900
a year      4069
a month      119
Name: count, dtype: int64

In [ ]:
import ast
from collections import Counter

# Convert description_tokens from text into actual Python lists
df['skills'] = df['description_tokens'].apply(ast.literal_eval)

# Count how many job postings mention each skill
skill_counts = Counter(
    skill
    for skills in df['skills'] #goes through the skills column one row at a time.
    for skill in skills #going inside each individual list.
)

# Show the 30 most requested skills
print("TOP 30 SKILLS")
print(skill_counts.most_common(30))

# Number of postings with at least one identified skill
print("\nPOSTINGS WITH SKILLS")
print((df['skills'].str.len() > 0).value_counts())

# Average number of identified skills per posting
print("\nAVERAGE SKILLS PER POSTING")
print(df['skills'].str.len().mean())

TOP 30 SKILLS
[('sql', 31006), ('excel', 19779), ('python', 18793), ('power_bi', 17420), ('tableau', 16823), ('r', 11342), ('sas', 5317), ('powerpoint', 4411), ('word', 4365), ('azure', 3887), ('snowflake', 3647), ('aws', 3636), ('spark', 3153), ('looker', 2670), ('go', 2361), ('spreadsheet', 2302), ('sap', 2238), ('scala', 2109), ('spss', 1882), ('jira', 1797), ('java', 1709), ('c', 1637), ('alteryx', 1620), ('outlook', 1484), ('hadoop', 1464), ('nosql', 1418), ('sharepoint', 1384), ('vba', 1333), ('javascript', 1315), ('gcp', 1295)]

POSTINGS WITH SKILLS
skills
True     48601
False    13352
Name: count, dtype: int64

AVERAGE SKILLS PER POSTING
3.2591642051232386

In [16]:
print("JUNIOR TITLES")
print(
    df[df['title'].str.contains('Junior', case=False, na=False)]['title']
    .value_counts()
    .head(20)
)

print("\nSENIOR TITLES")
print(
    df[df['title'].str.contains(r'Senior|Sr\.', case=False, na=False, regex=True)]['title']
    .value_counts()
    .head(20)
)

print("\nLEAD TITLES")
print(
    df[df['title'].str.contains('Lead', case=False, na=False)]['title']
    .value_counts()
    .head(20)
)

JUNIOR TITLES
title
Junior Data Analyst                                                                                                            213
Business Data Analyst (Junior)                                                                                                  35
Junior Data Scientist                                                                                                           21
Junior Data Analyst, Excel Experience Required - Work From Home                                                                 17
Data Analyst (Junior)                                                                                                           13
Junior Business Analyst                                                                                                          9
Junior Business Intelligence Analyst                                                                                             9
SynergisticIT is hiring: Junior Data/Business Analyst in Denver                                                                  8
Junior Safety Data Analyst                                                                                                       8
Remote Junior Data Analyst                                                                                                       7
Junior Analyst                                                                                                                   7
Junior data analyst                                                                                                              7
Data Analyst (Junior Role)                                                                                                       7
Junior Data Quality Analyst                                                                                                      6
Junior Data Analyst, Excel Experience Required – Work From Home in  Washington DC in Next Step Systems (job Id: 1676608285)      6
Junior Data Engineer                                                                                                             5
Junior Financial Data Analyst                                                                                                    5
Junior Freight Pay Data Analyst - EXCEL, Supply Chain. Finance                                                                   5
Junior Data/Business Analyst Job at SynergisticIT in Denver                                                                      4
Junior Data Analyst (Remote)                                                                                                     4
Name: count, dtype: int64

SENIOR TITLES
title
Senior Data Analyst                                                    1748
Sr. Data Analyst, Marketing Operations                                  271
Sr. Data Analyst                                                        240
Senior Data Analyst, Business Optimization                               99
Senior Data Scientist                                                    90
Senior, Data Analyst                                                     84
Senior Business Intelligence Analyst                                     70
Senior Business Data Analyst                                             63
Senior Performance Marketing (Data Analyst)                              59
Senior Financial Data Analyst                                            57
Senior Marketing Data Analyst                                            54
(USA) Senior, Data Analyst                                               45
Senior Data Analyst - Transportation Optimization                        42
(USA) Senior Data Analyst with Energy, Utilities and Sustainability      39
Senior Data Analyst (Remote)                                             38
Senior Data Analyst - Remote                                             37
Senior BI Analyst                                                        35
Senior Data Engineer                                                     35
Senior Data Analyst - Firm Analytics                                     33
Senior Healthcare Data Analyst                                           32
Name: count, dtype: int64

LEAD TITLES
title
Lead Data Analyst                                     428
Lead BI Analyst                                        50
Lead-Data Analyst                                      46
Data Analyst Lead                                      39
Lead Data Scientist                                    36
Lead Data Analyst - Full-time / Part-time              29
Data Integration Lead                                  27
Data Analytics Lead                                    22
Lead Data Science Analyst                              20
Data Governance Lead                                   16
Big Data Lead                                          16
Lead Data Engineer                                     15
Lead Master Data Analyst (Springdale, AR)              14
Lead Data Analytic Analyst                             13
Lead Data Analysis                                     12
Senior Data Analyst Lead, Corporate Vice President     12
Lead Healthcare Data Analyst                           12
Financial Data Analyst Lead                            11
Data Analyst Senior or Lead                            11
Data Lead                                              10
Name: count, dtype: int64

In [17]:
import numpy as np

df['seniority'] = np.select(
    [
        df['title'].str.contains('Lead', case=False, na=False),
        df['title'].str.contains(r'Senior|Sr\.?', case=False, na=False, regex=True),
        df['title'].str.contains('Junior', case=False, na=False)
    ],
    [
        'Lead',
        'Senior',
        'Junior'
    ],
    default='Other'
)

print("SENIORITY DISTRIBUTION")
print(df['seniority'].value_counts())

print("\nSENIORITY PERCENTAGE")
print((df['seniority'].value_counts(normalize=True) * 100).round(2))

SENIORITY DISTRIBUTION
seniority
Other     49011
Senior    10182
Lead       2100
Junior      660
Name: count, dtype: int64

SENIORITY PERCENTAGE
seniority
Other     79.11
Senior    16.44
Lead       3.39
Junior     1.07
Name: proportion, dtype: float64

In [18]:
print("TOP SKILLS BY SENIORITY")

for level in ['Junior', 'Senior', 'Lead']:
    print(f"\n--- {level} ---")
    
    level_skills = Counter(
        skill
        for skills in df.loc[df['seniority'] == level, 'skills']
        for skill in skills
    )
    
    print(level_skills.most_common(10))

TOP SKILLS BY SENIORITY

--- Junior ---
[('excel', 343), ('sql', 311), ('power_bi', 248), ('python', 242), ('tableau', 239), ('java', 107), ('r', 103), ('javascript', 69), ('c++', 65), ('docker', 49)]

--- Senior ---
[('sql', 7153), ('tableau', 4560), ('python', 3989), ('power_bi', 3805), ('excel', 3228), ('r', 2603), ('sas', 1159), ('spark', 1045), ('snowflake', 1018), ('looker', 941)]

--- Lead ---
[('sql', 1021), ('python', 625), ('tableau', 519), ('power_bi', 459), ('excel', 401), ('r', 337), ('azure', 198), ('aws', 193), ('sas', 180), ('snowflake', 176)]

In [19]:
skills_to_compare = ['sql', 'excel', 'python', 'power_bi', 'tableau', 'r',
                     'sas', 'azure', 'aws', 'snowflake']

skill_by_seniority = {}

for level in ['Junior', 'Senior', 'Lead']:
    level_data = df[df['seniority'] == level]
    total_jobs = len(level_data)

    skill_by_seniority[level] = {}

    for skill in skills_to_compare:
        count = sum(skill in skills for skills in level_data['skills'])
        percentage = (count / total_jobs) * 100
        skill_by_seniority[level][skill] = round(percentage, 2)

skill_by_seniority

{'Junior': {'sql': 47.12,
  'excel': 51.97,
  'python': 36.67,
  'power_bi': 36.82,
  'tableau': 36.21,
  'r': 15.61,
  'sas': 5.91,
  'azure': 4.24,
  'aws': 4.09,
  'snowflake': 2.42},
 'Senior': {'sql': 70.25,
  'excel': 31.7,
  'python': 39.18,
  'power_bi': 33.66,
  'tableau': 44.78,
  'r': 25.56,
  'sas': 11.38,
  'azure': 7.03,
  'aws': 7.23,
  'snowflake': 10.0},
 'Lead': {'sql': 48.62,
  'excel': 19.1,
  'python': 29.76,
  'power_bi': 20.48,
  'tableau': 24.71,
  'r': 16.05,
  'sas': 8.57,
  'azure': 9.43,
  'aws': 9.19,
  'snowflake': 8.38}}

In [ ]:
skill_seniority_df = pd.DataFrame(skill_by_seniority).T # converts to table and .T=transporse the table

skill_seniority_df

,sql,excel,python,power_bi,tableau,r,sas,azure,aws,snowflake
Junior,47.12,51.97,36.67,36.82,36.21,15.61,5.91,4.24,4.09,2.42
Senior,70.25,31.70,39.18,33.66,44.78,25.56,11.38,7.03,7.23,10.00
Lead,48.62,19.10,29.76,20.48,24.71,16.05,8.57,9.43,9.19,8.38

In [23]:
print("SALARY AVAILABILITY")
print(df['salary'].notna().value_counts())
print((df['salary'].notna().mean() * 100).round(2))

print("\nSALARY RATE")
print(df['salary_rate'].value_counts(dropna=False))

print("\nSTANDARDIZED SALARY")
print(df['salary_standardized'].describe())

print("\nSALARY BY SENIORITY")
print(
    df.groupby('seniority')['salary_standardized']
      .agg(['count', 'mean', 'median', 'min', 'max'])
      .round(2)
)

SALARY AVAILABILITY
salary
False    51865
True     10088
Name: count, dtype: int64
16.28

SALARY RATE
salary_rate
NaN        51865
an hour     5900
a year      4069
a month      119
Name: count, dtype: int64

STANDARDIZED SALARY
count     10088.000000
mean      92289.425683
std       43277.933820
min       15080.000000
25%       62400.000000
50%       88400.000000
75%      117500.000000
max      624000.000000
Name: salary_standardized, dtype: float64

SALARY BY SENIORITY
           count       mean    median      min       max
seniority
Junior        98   64018.68   52837.2  29120.0  115500.0
Lead         275  126375.41  130000.0  20800.0  475000.0
Other       8316   88930.99   81120.0  15080.0  624000.0
Senior      1399  107532.93   97400.0  18720.0  434500.0

In [24]:
salary_q1 = df['salary_standardized'].quantile(0.25)
salary_q3 = df['salary_standardized'].quantile(0.75)
salary_iqr = salary_q3 - salary_q1

upper_limit = salary_q3 + 1.5 * salary_iqr

print("Q1:", salary_q1)
print("Q3:", salary_q3)
print("IQR:", salary_iqr)
print("Upper outlier limit:", round(upper_limit, 2))

print("\nPotential high-salary outliers:")
print(
    df[df['salary_standardized'] > upper_limit]
    [['title', 'company_name', 'salary', 'salary_rate', 'salary_standardized']]
    .sort_values('salary_standardized', ascending=False)
    .head(20)
)

Q1: 62400.0
Q3: 117500.0
IQR: 55100.0
Upper outlier limit: 200150.0

Potential high-salary outliers:
                                                   title        company_name  \
22608                             Freelance Data Analyst              Upwork
45815                         Consulting from Data buyer              Upwork
3472      Quantitative Researcher - Fundamental Equities       Non-Disclosed
34966                 Cryptocurrency Market Data Analyst              Upwork
26273     Lead Quantitative Researcher - Equity Stat Arb  Algo Capital Group
26274     Lead Quantitative Researcher - Equity Stat Arb  Algo Capital Group
22699  Looking for a EXPERT Equity Research Analyst -...              Upwork
22700  Looking for a EXPERT Equity Research Analyst -...              Upwork
8776                        Sr. Data & Reporting Analyst      PCS Retirement
15714  Experienced Looker BI Data Analyst Consultant ...              Upwork
46243    Data Analyst for Ecommerce and Marketing Agency              Upwork
44830                                Analyze census data              Upwork
45593                            Cluster Analysis Expert              Upwork
38240                           Principal Data Scientist              Storm5
28805                 Data Science and Analytics, Policy           Anthropic
47804       Pre-Sales Data Scientist, Financial Services            Teradata
16921  Manager, Data Science, Analytics - New Vertica...            DoorDash
46248       Designing an Excel Scorecard for our Company              Upwork
45017                                       Data Analyst              Upwork
16918  Senior Director, Enabling Functions AI Data An...              Pfizer

                 salary salary_rate  salary_standardized
22608   100–500 an hour     an hour             624000.0
45815   150–400 an hour     an hour             572000.0
3472   450K–650K a year      a year             550000.0
34966    17–500 an hour     an hour             537680.0
26273  250K–700K a year      a year             475000.0
26274  250K–700K a year      a year             475000.0
22699   200–250 an hour     an hour             468000.0
22700   200–250 an hour     an hour             468000.0
8776    19K–850K a year      a year             434500.0
15714   150–200 an hour     an hour             364000.0
46243    10–300 an hour     an hour             322400.0
44830   100–200 an hour     an hour             312000.0
45593    50–250 an hour     an hour             312000.0
38240  275K–325K a year      a year             300000.0
28805  265K–315K a year      a year             290000.0
47804  230K–346K a year      a year             288000.0
16921       288K a year      a year             288000.0
46248    75–200 an hour     an hour             286000.0
45017    70–200 an hour     an hour             280800.0
16918  205K–342K a year      a year             273500.0

In [25]:
salary_clean = df[
    df['salary_standardized'].notna() &
    (df['salary_standardized'] <= upper_limit)
].copy()

print("Original salary records:", df['salary_standardized'].notna().sum())
print("Clean salary records:", len(salary_clean))
print("Removed as high-salary outliers:",
      df['salary_standardized'].notna().sum() - len(salary_clean))

print("\nCLEAN SALARY SUMMARY")
print(
    salary_clean['salary_standardized']
    .describe()
    .round(2)
)

print("\nCLEAN SALARY BY SENIORITY")
print(
    salary_clean.groupby('seniority')['salary_standardized']
    .agg(['count', 'mean', 'median'])
    .round(2)
)

Original salary records: 10088
Clean salary records: 9860
Removed as high-salary outliers: 228

CLEAN SALARY SUMMARY
count      9860.00
mean      88979.22
std       36628.90
min       15080.00
25%       62400.00
50%       87050.00
75%      114400.00
max      200000.00
Name: salary_standardized, dtype: float64

CLEAN SALARY BY SENIORITY
           count       mean    median
seniority
Junior        98   64018.68   52837.2
Lead         266  120904.79  128375.0
Other       8108   85238.19   80000.0
Senior      1388  106476.52   96500.0

In [26]:
print("WORK FROM HOME")
print(df['work_from_home'].value_counts(dropna=False))

print("\nWORK FROM HOME PERCENTAGE")
print(
    df['work_from_home']
    .value_counts(normalize=True, dropna=False)
    .mul(100)
    .round(2)
)

print("\nSCHEDULE TYPE")
print(df['schedule_type'].value_counts().head(15))

print("\nSCHEDULE TYPE PERCENTAGE")
print(
    df['schedule_type']
    .value_counts(normalize=True)
    .head(15)
    .mul(100)
    .round(2)
)

WORK FROM HOME
work_from_home
NaN     33973
True    27980
Name: count, dtype: int64

WORK FROM HOME PERCENTAGE
work_from_home
NaN     54.84
True    45.16
Name: proportion, dtype: float64

SCHEDULE TYPE
schedule_type
Full-time                               45082
Contractor                               9284
Contractor and Temp work                 3130
Full-time and Part-time                  1187
Part-time                                1144
Internship                                516
Full-time and Contractor                  349
Full-time and Temp work                   283
Full-time and Internship                  192
Temp work                                 169
Full-time, Part-time, and Internship       92
Full-time, Contractor, and Temp work       85
Part-time, Contractor, and Temp work       47
Part-time and Contractor                   30
Volunteer                                  27
Name: count, dtype: int64

SCHEDULE TYPE PERCENTAGE
schedule_type
Full-time                               73.06
Contractor                              15.05
Contractor and Temp work                 5.07
Full-time and Part-time                  1.92
Part-time                                1.85
Internship                               0.84
Full-time and Contractor                 0.57
Full-time and Temp work                  0.46
Full-time and Internship                 0.31
Temp work                                0.27
Full-time, Part-time, and Internship     0.15
Full-time, Contractor, and Temp work     0.14
Part-time, Contractor, and Temp work     0.08
Part-time and Contractor                 0.05
Volunteer                                0.04
Name: proportion, dtype: float64

In [27]:
print("UNIQUE LOCATIONS:", df['location'].nunique())

print("\nTOP LOCATIONS")
print(df['location'].value_counts(dropna=False).head(30))

print("\nMISSING LOCATIONS:", df['location'].isna().sum())

UNIQUE LOCATIONS: 1254

TOP LOCATIONS
location
 Anywhere                  18067
  United States            10011
Anywhere                    9915
United States               5547
Denver, CO                  1062
  Oklahoma City, OK         1028
  Kansas City, MO            840
Kansas City, MO              573
  Jefferson City, MO         550
Colorado Springs, CO         512
  Bentonville, AR            422
Oklahoma City, OK            409
Jefferson City, MO           371
Aurora, CO                   346
  Topeka, KS                 310
  Wichita, KS                307
  Tulsa, OK                  297
  Overland Park, KS          270
Englewood, CO                254
Columbia, MO                 218
  Springfield, MO            215
Tulsa, OK                    213
Wichita, KS                  179
Bentonville, AR              176
Boulder, CO                  173
  California, MO             165
Overland Park, KS            162
Greenwood Village, CO        141
Santa Fe, NM                 141
  Rogers, AR                 140
Name: count, dtype: int64

MISSING LOCATIONS: 37

In [28]:
df['location_clean'] = df['location'].str.strip()

print("Original unique locations:", df['location'].nunique())
print("Cleaned unique locations:", df['location_clean'].nunique())

print("\nTOP CLEANED LOCATIONS")
print(df['location_clean'].value_counts(dropna=False).head(30))

Original unique locations: 1254
Cleaned unique locations: 977

TOP CLEANED LOCATIONS
location_clean
Anywhere                 27982
United States            15558
Oklahoma City, OK         1437
Kansas City, MO           1413
Denver, CO                1062
Jefferson City, MO         921
Bentonville, AR            598
Colorado Springs, CO       512
Tulsa, OK                  510
Wichita, KS                486
Topeka, KS                 449
Overland Park, KS          432
Aurora, CO                 346
Springfield, MO            333
Columbia, MO               309
Englewood, CO              254
Springdale, AR             220
Kansas City, KS            208
California, MO             193
Rogers, AR                 193
Boulder, CO                173
Missouri                   172
Fayetteville, AR           165
Lenexa, KS                 156
Greenwood Village, CO      141
Santa Fe, NM               141
Edmond, OK                 139
Olathe, KS                 132
Missouri City, MO          108
Bella Vista, AR            101
Name: count, dtype: int64

In [29]:
df['location_type'] = df['location_clean'].replace({
    'Anywhere': 'Anywhere / Remote',
    'United States': 'United States / Unspecified'
})

print("LOCATION TYPE")
print(df['location_type'].value_counts().head(10))

print("\nTOP SPECIFIC LOCATIONS")
specific_locations = df[
    ~df['location_clean'].isin(['Anywhere', 'United States'])
]

print(
    specific_locations['location_clean']
    .value_counts()
    .head(20)
)

LOCATION TYPE
location_type
Anywhere / Remote              27982
United States / Unspecified    15558
Oklahoma City, OK               1437
Kansas City, MO                 1413
Denver, CO                      1062
Jefferson City, MO               921
Bentonville, AR                  598
Colorado Springs, CO             512
Tulsa, OK                        510
Wichita, KS                      486
Name: count, dtype: int64

TOP SPECIFIC LOCATIONS
location_clean
Oklahoma City, OK       1437
Kansas City, MO         1413
Denver, CO              1062
Jefferson City, MO       921
Bentonville, AR          598
Colorado Springs, CO     512
Tulsa, OK                510
Wichita, KS              486
Topeka, KS               449
Overland Park, KS        432
Aurora, CO               346
Springfield, MO          333
Columbia, MO             309
Englewood, CO            254
Springdale, AR           220
Kansas City, KS          208
California, MO           193
Rogers, AR               193
Boulder, CO              173
Missouri                 172
Name: count, dtype: int64

In [30]:
# Create the Jobs table

jobs_df = df[
    [
        'job_id',
        'title',
        'company_name',
        'location_clean',
        'location_type',
        'seniority',
        'schedule_type',
        'work_from_home',
        'salary_standardized'
    ]
].copy()

# Rename columns to make them easier to understand
jobs_df = jobs_df.rename(columns={
    'location_clean': 'location',
    'salary_standardized': 'salary_annual'
})


#  Create the Skills table

skills_df = df[
    ['job_id', 'skills']
].explode('skills')

skills_df = skills_df.rename(columns={
    'skills': 'skill'
})

# Remove rows where no skill was identified
skills_df = skills_df.dropna(subset=['skill'])

# Remove duplicate job-skill combinations
skills_df = skills_df.drop_duplicates()


# Check the final tables

print("JOBS TABLE")
print("Rows:", len(jobs_df))
print("Columns:", jobs_df.shape[1])
print(jobs_df.head())

print("\nSKILLS TABLE")
print("Rows:", len(skills_df))
print("Columns:", skills_df.shape[1])
print(skills_df.head())

JOBS TABLE
Rows: 61953
Columns: 9
                                              job_id  \
0  eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...
1  eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...
2  eyJqb2JfdGl0bGUiOiJBZXJvbmF1dGljYWwgRGF0YSBBbm...
3  eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgLSBDb25zdW...
4  eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgfCBXb3JrZm...

                                              title  \
0                                      Data Analyst
1                                      Data Analyst
2                         Aeronautical Data Analyst
3  Data Analyst - Consumer Goods - Contract to Hire
4               Data Analyst | Workforce Management

                 company_name       location                location_type  \
0                        Meta       Anywhere            Anywhere / Remote
1                         ATC  United States  United States / Unspecified
2  Garmin International, Inc.     Olathe, KS                   Olathe, KS
3                      Upwork       Anywhere            Anywhere / Remote
4                Krispy Kreme  United States  United States / Unspecified

  seniority schedule_type work_from_home  salary_annual
0     Other     Full-time           True       122000.0
1     Other     Full-time            NaN            NaN
2     Other     Full-time            NaN            NaN
3     Other    Contractor           True        41600.0
4     Other    Contractor            NaN       100000.0

SKILLS TABLE
Rows: 189382
Columns: 2
                                              job_id    skill
0  eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...  tableau
0  eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...        r
0  eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...   python
0  eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...      sql
2  eyJqb2JfdGl0bGUiOiJBZXJvbmF1dGljYWwgRGF0YSBBbm...      sql

In [31]:
print("Unique jobs:", jobs_df['job_id'].nunique())
print("Unique job IDs in skills table:", skills_df['job_id'].nunique())

missing_job_ids = ~skills_df['job_id'].isin(jobs_df['job_id'])

print("Skills linked to missing jobs:", missing_job_ids.sum())

print("\nJobs with at least one identified skill:",
      skills_df['job_id'].nunique())

print("Jobs without identified skills:",
      len(jobs_df) - skills_df['job_id'].nunique())

Unique jobs: 58775
Unique job IDs in skills table: 45972
Skills linked to missing jobs: 0

Jobs with at least one identified skill: 45972
Jobs without identified skills: 15981

In [32]:
duplicate_job_ids = jobs_df[
    jobs_df['job_id'].duplicated(keep=False)
].sort_values('job_id')

print("Rows involved in duplicate job IDs:",
      len(duplicate_job_ids))

print("Number of duplicated job IDs:",
      duplicate_job_ids['job_id'].nunique())

print("\nExample duplicated job IDs:")
print(
    duplicate_job_ids[
        ['job_id', 'title', 'company_name', 'location', 'schedule_type']
    ].head(20)
)

Rows involved in duplicate job IDs: 4162
Number of duplicated job IDs: 984

Example duplicated job IDs:
                                                  job_id  \
1183   eyJqb2JfdGl0bGUiOiI0OCBob3VyIGRlYWRsaW5lLCByZX...
1181   eyJqb2JfdGl0bGUiOiI0OCBob3VyIGRlYWRsaW5lLCByZX...
27477  eyJqb2JfdGl0bGUiOiIkNTAvaHIuIC1EYXRhIEFuYWx5c3...
28850  eyJqb2JfdGl0bGUiOiIkNTAvaHIuIC1EYXRhIEFuYWx5c3...
27481  eyJqb2JfdGl0bGUiOiIkNTAvaHIuIC1EYXRhIEFuYWx5c3...
30371  eyJqb2JfdGl0bGUiOiIkNTAvaHIuIC1EYXRhIEFuYWx5c3...
26489  eyJqb2JfdGl0bGUiOiIkNTAvaHIuIC1EYXRhIEFuYWx5c3...
26490  eyJqb2JfdGl0bGUiOiIkNTAvaHIuIC1EYXRhIEFuYWx5c3...
28913  eyJqb2JfdGl0bGUiOiIkNTAvaHIuIC1EYXRhIEFuYWx5c3...
28864  eyJqb2JfdGl0bGUiOiIkNTAvaHIuIC1EYXRhIEFuYWx5c3...
28866  eyJqb2JfdGl0bGUiOiIkNTAvaHIuIC1EYXRhIEFuYWx5c3...
28875  eyJqb2JfdGl0bGUiOiIkNTAvaHIuIC1EYXRhIEFuYWx5c3...
28907  eyJqb2JfdGl0bGUiOiIkNTAvaHIuIC1EYXRhIEFuYWx5c3...
29957  eyJqb2JfdGl0bGUiOiIkNTAvaHIuIC1EYXRhIEFuYWx5c3...
28881  eyJqb2JfdGl0bGUiOiIkNTAvaHIuIC1EYXRhIEFuYWx5c3...
28889  eyJqb2JfdGl0bGUiOiIkNTAvaHIuIC1EYXRhIEFuYWx5c3...
27470  eyJqb2JfdGl0bGUiOiIkNTAvaHIuIC1EYXRhIEFuYWx5c3...
502    eyJqb2JfdGl0bGUiOiIkNTAvaHIuIC1EYXRhIEFuYWx5c3...
28859  eyJqb2JfdGl0bGUiOiIkNTAvaHIuIC1EYXRhIEFuYWx5c3...
28924  eyJqb2JfdGl0bGUiOiIkNTAvaHIuIC1EYXRhIEFuYWx5c3...

                                                   title  company_name  \
1183   48 hour deadline, repricing strategy/data anal...        Upwork
1181   48 hour deadline, repricing strategy/data anal...        Upwork
27477  $50/hr. -Data Analyst | Remote | Short Term Co...  vmysmartpros
28850  $50/hr. -Data Analyst | Remote | Short Term Co...  vmysmartpros
27481  $50/hr. -Data Analyst | Remote | Short Term Co...  vmysmartpros
30371  $50/hr. -Data Analyst | Remote | Short Term Co...  vmysmartpros
26489  $50/hr. -Data Analyst | Remote | Short Term Co...  vmysmartpros
26490  $50/hr. -Data Analyst | Remote | Short Term Co...  vmysmartpros
28913  $50/hr. -Data Analyst | Remote | Short Term Co...  vmysmartpros
28864  $50/hr. -Data Analyst | Remote | Short Term Co...  vmysmartpros
28866  $50/hr. -Data Analyst | Remote | Short Term Co...  vmysmartpros
28875  $50/hr. -Data Analyst | Remote | Short Term Co...  vmysmartpros
28907  $50/hr. -Data Analyst | Remote | Short Term Co...  vmysmartpros
29957  $50/hr. -Data Analyst | Remote | Short Term Co...  vmysmartpros
28881  $50/hr. -Data Analyst | Remote | Short Term Co...  vmysmartpros
28889  $50/hr. -Data Analyst | Remote | Short Term Co...  vmysmartpros
27470  $50/hr. -Data Analyst | Remote | Short Term Co...  vmysmartpros
502    $50/hr. -Data Analyst | Remote | Short Term Co...  vmysmartpros
28859  $50/hr. -Data Analyst | Remote | Short Term Co...  vmysmartpros
28924  $50/hr. -Data Analyst | Remote | Short Term Co...  vmysmartpros

       location schedule_type
1183   Anywhere    Contractor
1181   Anywhere    Contractor
27477  Anywhere     Full-time
28850  Anywhere     Full-time
27481  Anywhere     Full-time
30371  Anywhere     Full-time
26489  Anywhere     Full-time
26490  Anywhere     Full-time
28913  Anywhere     Full-time
28864  Anywhere     Full-time
28866  Anywhere     Full-time
28875  Anywhere     Full-time
28907  Anywhere     Full-time
29957  Anywhere     Full-time
28881  Anywhere     Full-time
28889  Anywhere     Full-time
27470  Anywhere     Full-time
502    Anywhere     Full-time
28859  Anywhere     Full-time
28924  Anywhere     Full-time

In [33]:
jobs_df.to_csv("jobs_final.csv", index=False)
skills_df.to_csv("skills_final.csv", index=False)

print("Export complete.")
print("Jobs:", len(jobs_df))
print("Skills:", len(skills_df))

Export complete.
Jobs: 61953
Skills: 189382

In [34]:
import os

jobs_df.to_csv("jobs_final.csv", index=False)
skills_df.to_csv("skills_final.csv", index=False)

print("Current folder:", os.getcwd())
print("Jobs file exists:", os.path.exists("jobs_final.csv"))
print("Skills file exists:", os.path.exists("skills_final.csv"))

Current folder: c:\Users\Tasfia Samrin\Desktop\data-analysis\project
Jobs file exists: True
Skills file exists: True

In [1]:
import pandas as pd

check = pd.read_csv("jobs_final.csv")

print("Rows:", len(check))
print("Columns:", len(check.columns))
print(check.columns.tolist())

Rows: 61953
Columns: 9
['job_id', 'title', 'company_name', 'location', 'location_type', 'seniority', 'schedule_type', 'work_from_home', 'salary_annual']